version: "3"

services:
  fpm:
    build: # Info to build the Docker image
      context: . # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: Dockerfile-php # Specify the name of the Dockerfile
    environment: # You can use this section to set environment variables. But you can also use the .env file.
     - DATABASE_URL=mysql://dbuser:123@db:3306/dbname # Connection string for the database.
    volumes:
     - ./api/:/var/www/api/ # Location of the project for php-fpm. Note this should be the same for NGINX.
    networks:
     - symfony # Docker containers (services) that need to connect to each other should be on the same network.

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
     - ./api/:/var/www/api/
    ports:
     - 8001:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    networks:
     - symfony

  db:
    image: mysql:5.7.22
    environment:
    - MYSQL_ROOT_PASSWORD=123 # Setting the MYSQL credentials to root:root.
    volumes:
    - symfony_db:/var/lib/mysql:cached # Persist the database in a Docker volume.
    ports:
    - 3311:3306
    networks:
    - symfony

volumes:
  symfony_db:

networks:
 symfony:
