security:
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 12
  providers:
    in_memory: { memory: null }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
  access_control:
    - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, roles: IS_AUTHENTICATED_ANONYMOUSLY }